import LocalizedStrings from 'react-localization';
 
export default new LocalizedStrings({
  EN:{
    works:"Works",
    about:"About",
    contact:"Contact",
    headerFirstTitle:"Hi, my name is Alejandro Berbin and I'm a",
    headerSecondTitle:"Developer",
    slideDown:"Slide down",
    backend:"Backend",
    frontend:"Frontend",
    mobile:"Mobile",
    reactJs:"ReactJs",
    php:"PHP",
    laravel:"Laravel",
    wordpress:"Wordpress",
    reactNative:"ReactNative",
    vueJs:"VueJs",
    javascript:"Javascript",
    worksTitle:"Some of the projects I work on",
    worksDescription: "There are from web projects, like mobile and jobs like CM.",
    socialNetwork: "My social networks:",
    copyright: "The last update was %d days ago",
    contactMe: "Contact Me:",
    PortfolioVueJS: "8 .Portfolio VueJS",
    comingSoon: "Coming Soon",
    thisIsMeFace: "This is me Face",
    seeMore: "Ver mas",
    atanchaDesc: "Desarrolle en la aplicacion web de Regularizacion de tierras, usando CakePHP. Ademas que era el encargado del modulo de visualizacion de datos geoespaciales.",
    agroInfoDesc: "Esta web tenia como objetivo mostrar datos basicos a los bancos de Venezuela, para dar creditos a los campesinos, realice pequenos arreglos en este projecto.",
    intiApiDesc: "Esta aplicacion era la api encargada de suministrar los datos a la web de AgroInfo.",
  
  },
  ES: {
    works:"Trabajos",
    about:"Acerca de mi",
    contact:"Contacto",
    headerFirstTitle:"Hola, me llamo Alejandro Berbin y soy un Desarrollador",
    headerSecondTitle:"",
    slideDown:"Desliza hacia abajo",
    backend:"Backend",
    frontend:"Frontend",
    mobile:"Mobile",
    reactJs:"ReactJs",
    php:"PHP",
    laravel:"Laravel",
    wordpress:"Wordpress",
    reactNative:"React Native",
    vueJs:"VueJs",
    javascript:"Javascript",
    worksTitle:"Some of the projects I work on",
    worksDescription: "There are from web projects, like mobile and jobs like CM.",
    socialNetwork: "My social networks:",
    copyright: "The last update was %d days ago",
    contactMe: "Contact Me",
    PortfolioVueJS: "Portfolio VueJS",
    comingSoon: "Coming Soon",
    thisIsMeFace: "Esta es mi cara",
    atanchaDesc: "Desarrolle en la aplicacion web de Regularizacion de tierras, usando CakePHP. Ademas que era el encargado del modulo de visualizacion de datos geoespaciales."
  }
});